version: 1
handlers:
  console:
    class: logging.StreamHandler
    stream: ext://sys.stderr
    formatter: basic
  file:
    class: logging.FileHandler
    filename: exec.log
    encoding: utf-8
    formatter: verbose
formatters:
  basic:
    style: "%"
    format: "%(levelname)s %(message)s"
  verbose:
    style: "%"
    format: "%(levelname)s %(asctime)s %(module)s %(process)d %(thread)d %(message)s"
    datefmt: "%Y-%m-%d %H:%M:%S"
loggers:
  debug:
    handlers: [console, file]
    level: DEBUG
    propagate: False
root:
  handlers: [console]
  level: DEBUG