version: 1
handlers:
  console:
    class: logging.StreamHandler
    stream: ext://sys.stderr
    formatter: basic
formatters:
  basic:
    style: "%"
    format: "%(asctime)s %(name)s : %(levelname)s : %(message)s"
    datefmt: "%Y-%m-%d %H:%M:%S"
loggers:
  debug:
    handlers: [console]
    level: DEBUG
    propagate: False
root:
  handlers: [console]
  level: DEBUG